vich_uploader:
    db_driver: orm

    mappings:
        food_image:
            uri_prefix: /images/foods
            upload_destination: '%kernel.project_dir%/public/images/foods'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
